# Generated by Django 5.1.7 on 2025-03-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='FeedingRecord',
        ),
    ]
